name: Merge
on:
  push:
    branches: master

jobs:
  nugets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Pack NuGet
      run: dotnet pack --configuration Release -v m --output nupkgs -p:PackageVersion=1.99.$GITHUB_RUN_NUMBER-preview
    - name: Push NuGets
      run: dotnet nuget push "**/Frank.Libraries.*.1.99.$GITHUB_RUN_NUMBER-preview.nupkg" -k ${{ secrets.NugetKey }} -s https://api.nuget.org/v3/index.json
